"""empty message

Revision ID: a10b8ca51e91
Revises: e88834405416
Create Date: 2024-07-20 17:11:30.240115

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a10b8ca51e91"
down_revision: Union[str, None] = "e88834405416"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("msg_ids", sa.ARRAY(sa.Integer()), nullable=True),
        sa.ForeignKeyConstraint(["employee_id"], ["employee.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "facility_employee_relationship",
        "employee_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "facility_employee_relationship",
        "facility_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column("file", "report_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("pause", "report_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("report", "employee_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("report", "facility_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("report", "facility_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("report", "employee_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("pause", "report_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("file", "report_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "facility_employee_relationship",
        "facility_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "facility_employee_relationship",
        "employee_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.drop_table("message")
    # ### end Alembic commands ###
