"""empty message

Revision ID: 4e5445e2e33c
Revises: 1e22f6beba91
Create Date: 2024-07-20 12:41:55.647443

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4e5445e2e33c"
down_revision: Union[str, None] = "1e22f6beba91"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "facility_employee_relationship",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=True),
        sa.Column("facility_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["employee_id"], ["employee.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["facility_id"], ["facility.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pause",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("report_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["report_id"], ["report.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("facility_user_relationship")
    op.drop_table("client_action_log")
    op.alter_column("facility", "active", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column(
        "report",
        "shift_end",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "report",
        "shift_end",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column("facility", "active", existing_type=sa.BOOLEAN(), nullable=False)
    op.create_table(
        "client_action_log",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("action", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("client_chat_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["client_chat_id"],
            ["employee.chat_id"],
            name="client_action_log_client_chat_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="client_action_log_pkey"),
    )
    op.create_table(
        "facility_user_relationship",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("employee_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("facility_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employee.id"],
            name="facility_user_relationship_employee_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facility.id"],
            name="facility_user_relationship_facility_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="facility_user_relationship_pkey"),
    )
    op.drop_table("pause")
    op.drop_table("facility_employee_relationship")
    # ### end Alembic commands ###
