"""empty message

Revision ID: 05df84b44d2b
Revises: 4e5445e2e33c
Create Date: 2024-07-20 15:35:06.903273

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "05df84b44d2b"
down_revision: Union[str, None] = "4e5445e2e33c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("report", "description", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("report", "description", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
