"""empty message

Revision ID: 6cdcd372b28f
Revises: a10b8ca51e91
Create Date: 2024-07-20 17:25:49.446037

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6cdcd372b28f"
down_revision: Union[str, None] = "a10b8ca51e91"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("message", sa.Column("chat_id", sa.BigInteger(), nullable=False))
    op.drop_constraint("message_employee_id_fkey", "message", type_="foreignkey")
    op.create_foreign_key(
        None, "message", "employee", ["chat_id"], ["chat_id"], ondelete="CASCADE"
    )
    op.drop_column("message", "employee_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "message",
        sa.Column("employee_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "message", type_="foreignkey")
    op.create_foreign_key(
        "message_employee_id_fkey",
        "message",
        "employee",
        ["employee_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("message", "chat_id")
    # ### end Alembic commands ###
